#!/usr/bin/env bash

iDIR="$HOME/.config/hypr/scripts/icons"

# Get brightness
get_backlight() {
	echo $(brightnessctl -m | cut -d, -f4)
}

# Get icons
get_icon() {
	current=$(get_backlight | sed 's/%//')
	if   [[ "$current" -le "20" ]]; then
		echo "$iDIR/brightness-3.png"
	elif [[ "$current" -le "40" ]]; then
		echo "$iDIR/brightness-4.png"
	elif [[ "$current" -le "60" ]]; then
		echo "$iDIR/brightness-5.png"
	elif [[ "$current" -le "80" ]]; then
		echo "$iDIR/brightness-6.png"
	else
		echo "$iDIR/brightness-7.png"
	fi
}

# Notify
notify_user() {
    notify-send -e -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" -t 555 -h int:value:"$(get_backlight)" "Brightness : $(get_backlight)"
}

# Change brightness
change_backlight() {
	brightnessctl set "$1" && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	change_backlight "+10%"
elif [[ "$1" == "--dec" ]]; then
	change_backlight "10%-"
elif [[ "$1" == "--get-icon" ]]; then
    get_icon
elif [[ "$1" == "--notify" ]]; then
    notify_user
else
    get_backlight && notify_user
fi
